// src/lib/components/AdSpace.svelte
<script lang="ts">
import { envBool } from "$lib/utils/env-helper";
import { sha3_256 } from "@noble/hashes/sha3";
import { bytesToHex } from "@noble/hashes/utils";
import { onDestroy, onMount } from "svelte";
import PrivacyIcon from "./icons/PrivacyIcon.svelte";
import log from "$lib/utils/logger";

type UnitType = "bottom_rail" | "sky_atf" | "med_rect_atf" | "right_rail";

interface Props {
    name: string;
    type: UnitType;
    wrapperClasses?: string;
}

const unitSize: { [type in UnitType]: { width: number; height: number } } = {
    bottom_rail: { width: 320, height: 50 },
    sky_atf: { width: 160, height: 600 },
    med_rect_atf: { width: 300, height: 250 },
    right_rail: { width: 120, height: 600 },
};

const { name, type, wrapperClasses }: Props = $props();

const adsEnabled = envBool("DB_ENABLE_ADS");
const displayPlaceholders = envBool("DB_DISPLAY_AD_PLACEHOLDERS");

const selectorName = $derived.by(() => {
    const base = name + ":" + type;
    const hash = bytesToHex(sha3_256(base));
    return `dbu_${hash}`;
});

const size = $derived(unitSize[type]);

onMount(async () => {
    if (!adsEnabled || displayPlaceholders) {
        return;
    }

    try {
        await window.ramp.addUnits([
            {
                selectorId: selectorName,
                type,
            },
        ]);
        window.ramp.displayUnits();
        log.debug(`ramp: initialized unit ${name} (${type})`);
    } catch (error) {
        log.error("ramp: could not add  unit", { error });
        window.ramp.displayUnits();
    }
});

onDestroy(() => {
    if (!adsEnabled || displayPlaceholders) {
        return;
    }

    const elem = document.getElementById(selectorName);

    if (!elem) {
        return;
    }

    window.ramp.destroyUnits(selectorName).then(() => {
        window.ramp.processPage(window.location.pathname);
    });
});
</script>

{#if adsEnabled && displayPlaceholders}
    <div class={"ads " + (wrapperClasses ?? "")}>
        <div
            class="flex justify-center items-center border-dashed border-4 border-primary m-2"
            style={`width: ${size.width}px; height: ${size.height}px`}
        >
            <div class="text-primary scale-[2.0]">
                <PrivacyIcon />
            </div>
        </div>
    </div>
{/if}

{#if adsEnabled && !displayPlaceholders}
    <div class={"ads " + (wrapperClasses ?? "")}>
        <div id={selectorName}></div>
    </div>
{/if}

// src/components/AdSpace.tsx
import { FeaturedVideo } from "@mui/icons-material";
import { Box, useTheme } from "@mui/material";
import { eventsAtom, playwireAddInitializedUnit } from "@src/state/events";
import { adsEnabled } from "@src/utils/env-tools";
import log from "@src/utils/logger";
import { useAtom } from "jotai";
import md5 from "md5";
import React, { useEffect } from "react";

export enum UnitType {
    BottomRail = "bottom_rail",
    Skyscraper = "sky_atf",
    MediumRect = "med_rect_atf",
    RightRail = "right_rail",
}

export const adSpaceSize = {
    [UnitType.BottomRail]: { height: 50, width: 320 },
    [UnitType.Skyscraper]: { height: 600, width: 160 },
    [UnitType.MediumRect]: { height: 250, width: 300 },
    [UnitType.RightRail]: { height: 600, width: 120 },
};

interface AdSpaceProps {
    name: string;
    unitType: UnitType;
}

const AdSpace: React.FC<AdSpaceProps> = ({ name, unitType }) => {
    const theme = useTheme();

    const [events, setEvents] = useAtom(eventsAtom);

    const selectorName = `dbu_${md5(name + unitType.toString())}`;

    const size = unitType in adSpaceSize ? adSpaceSize[unitType as keyof typeof adSpaceSize] : null;

    useEffect(() => {
        if (events.playwireInitializedUnits.indexOf(name) > -1) {
            log.error(`ramp: Unit ${name} (${unitType}) has already been initialized...`);
            return;
        }

        if (DB_DISPLAY_AD_PLACEHOLDERS) {
            setEvents(playwireAddInitializedUnit(name));
            log.debug(`not ramp: initialized unit ${name} (${unitType})`);
        }

        if (!adsEnabled) {
            return;
        }

        if (!events.playwireSetupHasFinished) {
            return;
        }

        const initUnit = async () => {
            try {
                await window.ramp.addUnits([
                    {
                        selectorId: selectorName,
                        type: unitType,
                    },
                ]);
                window.ramp.displayUnits();
            } catch (error) {
                log.error("ramp: could not add unit", { error });
                window.ramp.displayUnits();
            }

            setEvents(playwireAddInitializedUnit(name));
            log.debug(`ramp: initialized unit ${name} (${unitType})`);
        };
        initUnit();

        return () => {
            window.ramp.destroyUnits(selectorName).then(() => window.ramp.processPage(window.location.pathname));
        };
    }, [events.playwireSetupHasFinished, events.playwireInitializedUnits, selectorName, unitType, setEvents, name]);

    if (DB_DISPLAY_AD_PLACEHOLDERS) {
        return (
            <Box
                id={selectorName}
                sx={{
                    alignItems: "center",
                    background: theme.palette.background.default,
                    border: `5px dashed ${theme.palette.primary.main}`,
                    color: theme.palette.primary.main,
                    display: "flex",
                    height: `${size?.height}px`,
                    justifyContent: "center",
                    m: 1,
                    p: 1,
                    width: `${size?.width}px`,
                }}
            >
                <FeaturedVideo />
            </Box>
        );
    }

    if (!adsEnabled) {
        return null;
    }

    return <div id={selectorName} />;
};

export default React.memo(AdSpace);
